[build]
builder = "railpack"

[env]
PYTHON_VERSION = "3.12.6"

[packages]
# These are needed for Playwright headless Chromium
apt = [
  "libnss3",
  "libnspr4",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libx11-6",
  "libxcomposite1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxrandr2",
  "libgbm1",
  "libpango-1.0-0",
  "libcairo2",
  "libasound2",
  "libatspi2.0-0",
  "libglib2.0-0",
  "libgobject-2.0-0",
  "libdbus-1-3",
  "libcups2",
  "libexpat1",
  "libxcb1",
  "libxkbcommon0",
  "fonts-liberation",
  "libdrm2"
]
